export const INCREMENT = 'INCREMENT';
export const INCREMENTBYTEN = 'INCREMENTBYTEN';
export const DECREMENT = 'DECREMENT';
export const INCREMENTASYNC = 'INCREMENTASYNC';
export const ISLOADING = 'ISLOADING';